services:
  movieapi.application:
    image: ${DOCKER_REGISTRY-}movieapiapplication
    build:
      context: .
      dockerfile: MovieAPI.Application/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - fakeserver 
  fakeserver:
    build:
      context: ./FakeServer
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./FakeServer:/app
    command: json-server --watch db.json --routes routes.json --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"