services:
  movieapi.application:
    image: ${DOCKER_REGISTRY-}movieapiapplication
    build:
      context: .
      dockerfile: MovieAPI.Application/Dockerfile
    depends_on:
      - fakeserver 
    environment:
      - HttpMovieRepository__BaseURL=https://api.themoviedb.org/3/
      - HttpMovieRepository__UserAgent=movie-app-rb