services:
  movieapi.application:
    image: ${DOCKER_REGISTRY-}movieapiapplication
    build:
      context: .
      dockerfile: MovieAPI.Application/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"